from html import escape
from string import Template
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from functions.assessment import (
    GRADE_ADEQUATE,
    GRADE_CRITICAL,
    GRADE_STRONG,
    GRADE_WEAK,
    CompanyAssessment,
    assess_company,
)
from functions.config import APP_NAME, IS_NET_INCOME, IS_REVENUE
from functions.datamodel import FinancialDataModel, read_item
from functions.narrative import SECTION_ORDER, generate_executive_narrative
from functions.quality import SEVERITY_CRITICAL, evaluate_red_flags
from functions.ratios import EBITDA_MARGIN, ROE, compute_all_ratios, read_ratio

VERDICT_CLASS = {
    GRADE_STRONG: "verdict-strong",
    GRADE_ADEQUATE: "verdict-adequate",
    GRADE_WEAK: "verdict-weak",
    GRADE_CRITICAL: "verdict-critical",
}

_DOCUMENT = Template(
    """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$app_name Research Memo - $company</title>
<style>
  :root {
    --ink: #0F172A;
    --muted: #64748B;
    --line: #E2E8F0;
    --accent: #10B981;
    --surface: #F1F5F9;
  }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    line-height: 1.6;
    color: var(--ink);
    background: #F8FAFC;
    margin: 0;
    padding: 40px 20px;
  }
  .container {
    max-width: 940px;
    margin: 0 auto;
    background: #FFFFFF;
    padding: 48px;
    border: 1px solid var(--line);
    border-radius: 8px;
  }
  header { border-bottom: 3px solid var(--accent); padding-bottom: 20px; margin-bottom: 32px; }
  header h1 { margin: 0; font-size: 26px; letter-spacing: -0.01em; }
  header .meta { color: var(--muted); font-size: 14px; margin-top: 6px; }
  .kpi-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; margin-bottom: 36px; }
  .kpi { background: var(--surface); padding: 16px; border-radius: 6px; border-left: 4px solid var(--accent); }
  .kpi .label { font-size: 11px; color: var(--muted); text-transform: uppercase; letter-spacing: 0.06em; }
  .kpi .value { font-size: 20px; font-weight: 600; margin-top: 6px; }
  h2 { font-size: 17px; border-bottom: 1px solid var(--line); padding-bottom: 8px; margin-top: 36px; }
  p { margin: 12px 0; }
  .table-wrap { overflow-x: auto; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0 28px; font-size: 13px; }
  th, td { padding: 9px 12px; text-align: right; border-bottom: 1px solid var(--line); }
  th { background: #1E293B; color: #FFFFFF; font-weight: 600; }
  th:first-child, td:first-child { text-align: left; }
  .severity { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
  .severity-critical { background: #FEE2E2; color: #991B1B; }
  .severity-warning { background: #FEF3C7; color: #92400E; }
  .empty { color: var(--muted); font-style: italic; }
  .verdict { border: 1px solid var(--line); border-left-width: 5px; border-radius: 6px; padding: 18px 22px; margin-bottom: 28px; background: var(--surface); }
  .verdict-grade { font-size: 18px; font-weight: 700; margin-bottom: 8px; }
  .verdict-body { font-size: 14px; }
  .verdict-strong { border-left-color: #16A34A; }
  .verdict-adequate { border-left-color: #0891B2; }
  .verdict-weak { border-left-color: #D97706; }
  .verdict-critical { border-left-color: #DC2626; }
  .verdict-unknown { border-left-color: #94A3B8; }
  .caveats { font-size: 13px; color: var(--muted); padding-left: 20px; }
  .caveats li { margin-bottom: 6px; }
  footer { margin-top: 44px; padding-top: 20px; border-top: 1px solid var(--line); text-align: center; font-size: 12px; color: var(--muted); }
  @media print { body { padding: 0; background: #FFFFFF; } .container { border: 0; padding: 0; } }
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>$app_name Equity Research Memo</h1>
    <div class="meta">$company ($ticker) &middot; $sector &middot; Reporting currency $currency</div>
  </header>

  <div class="kpi-grid">$kpi_cards</div>

  <div class="verdict $verdict_class">
    <div class="verdict-grade">Overall verdict: $verdict_grade</div>
    <div class="verdict-body">$verdict_text</div>
  </div>

  <h2>Assessment by dimension</h2>
  $dimension_table

  $narrative_sections

  <h2>Accounting Quality Findings</h2>
  $red_flag_table

  <h2>Normalized Income Statement</h2>
  <div class="table-wrap">$income_table</div>

  <h2>Financial Ratios</h2>
  <div class="table-wrap">$ratio_table</div>

  <h2>Data Quality and Assumptions</h2>
  $caveat_list

  <footer>Generated by $app_name from $source &middot; For educational and research use only</footer>
</div>
</body>
</html>
"""
)


def export_report_to_html(
    model: FinancialDataModel,
    forecast_model: Optional[FinancialDataModel] = None,
) -> str:
    narratives = generate_executive_narrative(model)
    ratios = compute_all_ratios(model)
    red_flags = evaluate_red_flags(model)
    assessment = assess_company(model)
    reporting_model = forecast_model if forecast_model is not None else model
    latest_year = model.years[-1] if model.years else "N/A"

    return _DOCUMENT.substitute(
        app_name=escape(APP_NAME),
        company=escape(model.company_name),
        ticker=escape(model.ticker),
        sector=escape(model.metadata.get("Sector", "N/A")),
        currency=escape(model.currency),
        source=escape(model.source),
        kpi_cards=_render_kpi_cards(model, ratios, latest_year),
        verdict_class=VERDICT_CLASS.get(assessment.grade, "verdict-unknown"),
        verdict_grade=escape(f"{assessment.grade} ({assessment.score:.0f} out of 100)"),
        verdict_text=escape(assessment.verdict),
        dimension_table=_render_dimensions(assessment),
        narrative_sections=_render_narrative(narratives),
        red_flag_table=_render_red_flags(red_flags),
        income_table=_render_dataframe(reporting_model.income_statement),
        ratio_table=_render_dataframe(ratios),
        caveat_list=_render_caveats(assessment.caveats),
    )


def _render_dimensions(assessment: CompanyAssessment) -> str:
    rows = "".join(
        "<tr>"
        f"<td>{escape(dimension.name)}</td>"
        f"<td>{escape(dimension.grade)}</td>"
        f"<td>{'n/a' if np.isnan(dimension.score) else f'{dimension.score:.0f}'}</td>"
        f"<td>{escape(dimension.trend)}</td>"
        f"<td>{escape(dimension.verdict)}</td>"
        "</tr>"
        for dimension in assessment.dimensions
    )

    return (
        '<div class="table-wrap"><table><thead><tr>'
        "<th>Dimension</th><th>Grade</th><th>Score</th><th>Trend</th><th>Reasoning</th>"
        f"</tr></thead><tbody>{rows}</tbody></table></div>"
    )


def _render_caveats(caveats: List[str]) -> str:
    if not caveats:
        return '<p class="empty">No caveats were recorded for this dataset.</p>'

    items = "".join(f"<li>{escape(caveat)}</li>" for caveat in caveats)

    return f'<ul class="caveats">{items}</ul>'


def _render_kpi_cards(model: FinancialDataModel, ratios, latest_year: str) -> str:
    cards = [
        (f"Revenue ({latest_year})", _number(read_item(model.income_statement, IS_REVENUE, latest_year))),
        (f"Net income ({latest_year})", _number(read_item(model.income_statement, IS_NET_INCOME, latest_year))),
        ("EBITDA margin", _percent(read_ratio(ratios, EBITDA_MARGIN, latest_year))),
        ("Return on equity", _percent(read_ratio(ratios, ROE, latest_year))),
    ]

    return "".join(
        f'<div class="kpi"><div class="label">{escape(label)}</div>'
        f'<div class="value">{escape(value)}</div></div>'
        for label, value in cards
    )


def _render_narrative(narratives: Dict[str, str]) -> str:
    blocks = []

    for section in SECTION_ORDER:
        if section not in narratives:
            continue

        blocks.append(f"<h2>{escape(section)}</h2><p>{escape(narratives[section])}</p>")

    return "\n  ".join(blocks)


def _render_red_flags(red_flags: List[Dict[str, str]]) -> str:
    if not red_flags:
        return '<p class="empty">No forensic findings were raised by the rule set.</p>'

    rows = []

    for flag in red_flags:
        severity_class = (
            "severity-critical" if flag["severity"] == SEVERITY_CRITICAL else "severity-warning"
        )
        rows.append(
            "<tr>"
            f"<td>{escape(flag['rule_id'])}</td>"
            f"<td>{escape(flag['rule_name'])}</td>"
            f'<td><span class="severity {severity_class}">{escape(flag["severity"])}</span></td>'
            f"<td>{escape(flag['observation'])}</td>"
            "</tr>"
        )

    return (
        '<div class="table-wrap"><table><thead><tr>'
        "<th>Rule</th><th>Finding</th><th>Severity</th><th>Observation</th>"
        "</tr></thead><tbody>" + "".join(rows) + "</tbody></table></div>"
    )


def _render_dataframe(df: pd.DataFrame) -> str:
    if df is None or df.empty:
        return '<p class="empty">No data available.</p>'

    return df.to_html(border=0, float_format=lambda value: f"{value:,.2f}", na_rep="n/a")


def _number(value: float) -> str:
    return "n/a" if value is None or np.isnan(value) else f"{value:,.1f}"


def _percent(value: float) -> str:
    return "n/a" if value is None or np.isnan(value) else f"{value:,.1f}%"
